## YOUR TURN: Exchange rates
Start with url = 'https://api.exchangeratesapi.io/latest?base=NOK'

Q1: What is the average exchange rate value this search returns?

The documentation for this database (how to search it, change parameters, etc.)

Q2: Change the base to Euros, then tell me how many Japanese Yen is in a euro.

Q3: What was the number of Yen per Euro on Jan 2, 2018?

Q4: Bonus, prof can show: Get a time series of EURJPY from 2018 through 2019.

AFTER CLASS PRACTICE:

Rewrite our code for Q1-Q4 using requests_html to the extent possible. If and when you succeed, email your solution to me!

In [1]:
import pandas as pd
import requests 
from requests_html import HTMLSession
session=HTMLSession()

## NEW Q1

In [2]:
#Q1 Redone, Get Mean 
from requests_html import HTMLSession
session=HTMLSession()
r=session.get('https://api.exchangeratesapi.io/latest?base=NOK')
r.json()['rates']
pd.DataFrame(r.json()).describe()

             rates
count    33.000000
mean     53.012272
std     267.329070
min       0.078083
25%       0.174402
50%       0.679267
75%       3.180314
max    1537.609124

## New Q2

In [6]:
#Q2 Redone, Change base currency
from requests_html import HTMLSession
session=HTMLSession()
url = 'https://api.exchangeratesapi.io/latest?base=EUR'
r=requests.get(url)
pd.DataFrame(r.json())

           rates base        date
AUD      1.74440  EUR  2020-04-09
BGN      1.95580  EUR  2020-04-09
BRL      5.59560  EUR  2020-04-09
CAD      1.52650  EUR  2020-04-09
CHF      1.05580  EUR  2020-04-09
CNY      7.67090  EUR  2020-04-09
CZK     26.90900  EUR  2020-04-09
DKK      7.46570  EUR  2020-04-09
GBP      0.87565  EUR  2020-04-09
HKD      8.42590  EUR  2020-04-09
HRK      7.61750  EUR  2020-04-09
HUF    354.76000  EUR  2020-04-09
IDR  17243.21000  EUR  2020-04-09
ILS      3.89190  EUR  2020-04-09
INR     82.92750  EUR  2020-04-09
ISK    155.90000  EUR  2020-04-09
JPY    118.33000  EUR  2020-04-09
KRW   1322.49000  EUR  2020-04-09
MXN     26.03210  EUR  2020-04-09
MYR      4.71360  EUR  2020-04-09
NOK     11.21430  EUR  2020-04-09
NZD      1.81280  EUR  2020-04-09
PHP     54.93900  EUR  2020-04-09
PLN      4.55860  EUR  2020-04-09
RON      4.83300  EUR  2020-04-09
RUB     80.69000  EUR  2020-04-09
SEK     10.94550  EUR  2020-04-09
SGD      1.54790  EUR  2020-04-09
THB     35.66500  EUR  2020-04-09
TRY      7.32330  EUR  2020-04-09
USD      1.08670  EUR  2020-04-09
ZAR     19.63830  EUR  2020-04-09

# New Q3

In [8]:
from requests_html import HTMLSession
session=HTMLSession()
url = 'https://api.exchangeratesapi.io/history?start_at=2018-01-02&end_at=2018-01-02'

r=requests.get('https://api.exchangeratesapi.io/history?start_at=2018-01-02&end_at=2018-01-02')
r=requests.get(url)
pd.DataFrame(r.json())
r.json()['rates']['2018-01-02']['JPY']

135.35

# New Q4

In [7]:
from requests_html import HTMLSession
session=HTMLSession()
url = 'https://api.exchangeratesapi.io/history?start_at=2018-01-02&end_at=2019-12-31&symbols=JPY'

r=requests.get('https://api.exchangeratesapi.io/history?start_at=2018-01-02&end_at=2019-12-31&symbols=JPY')
r=requests.get(url)
df=pd.DataFrame(r.json())
df['EURJPY']=df['rates'].apply(lambda x: x.get('JPY'))
df

                      rates    start_at base      end_at  EURJPY
2018-01-02  {'JPY': 135.35}  2018-01-02  EUR  2019-12-31  135.35
2018-01-03  {'JPY': 134.97}  2018-01-02  EUR  2019-12-31  134.97
2018-01-04  {'JPY': 135.92}  2018-01-02  EUR  2019-12-31  135.92
2018-01-05  {'JPY': 136.45}  2018-01-02  EUR  2019-12-31  136.45
2018-01-08  {'JPY': 135.34}  2018-01-02  EUR  2019-12-31  135.34
2018-01-09  {'JPY': 134.31}  2018-01-02  EUR  2019-12-31  134.31
2018-01-10  {'JPY': 133.62}  2018-01-02  EUR  2019-12-31  133.62
2018-01-11  {'JPY': 134.19}  2018-01-02  EUR  2019-12-31  134.19
2018-01-12  {'JPY': 134.88}  2018-01-02  EUR  2019-12-31  134.88
2018-01-15  {'JPY': 135.81}  2018-01-02  EUR  2019-12-31  135.81
2018-01-16   {'JPY': 135.4}  2018-01-02  EUR  2019-12-31  135.40
2018-01-17  {'JPY': 135.21}  2018-01-02  EUR  2019-12-31  135.21
2018-01-18  {'JPY': 136.07}  2018-01-02  EUR  2019-12-31  136.07
2018-01-19  {'JPY': 135.54}  2018-01-02  EUR  2019-12-31  135.54
2018-01-22  {'JPY': 135.66}  2018-01-02  EUR  2019-12-31  135.66
2018-01-23  {'JPY': 135.35}  2018-01-02  EUR  2019-12-31  135.35
2018-01-24  {'JPY': 135.13}  2018-01-02  EUR  2019-12-31  135.13
2018-01-25  {'JPY': 135.12}  2018-01-02  EUR  2019-12-31  135.12
2018-01-26  {'JPY': 135.95}  2018-01-02  EUR  2019-12-31  135.95
2018-01-29  {'JPY': 134.75}  2018-01-02  EUR  2019-12-31  134.75
2018-01-30  {'JPY': 134.98}  2018-01-02  EUR  2019-12-31  134.98
2018-01-31   {'JPY': 135.6}  2018-01-02  EUR  2019-12-31  135.60
2018-02-01  {'JPY': 136.62}  2018-01-02  EUR  2019-12-31  136.62
2018-02-02  {'JPY': 137.22}  2018-01-02  EUR  2019-12-31  137.22
2018-02-05  {'JPY': 136.67}  2018-01-02  EUR  2019-12-31  136.67
2018-02-06  {'JPY': 134.97}  2018-01-02  EUR  2019-12-31  134.97
2018-02-07  {'JPY': 134.84}  2018-01-02  EUR  2019-12-31  134.84
2018-02-08  {'JPY': 134.31}  2018-01-02  EUR  2019-12-31  134.31
2018-02-09  {'JPY': 133.59}  2018-01-02  EUR  2019-12-31  133.59
2018-02-12  {'JPY': 133.23}  2018-01-02  EUR  2019-12-31  133.23
...                     ...         ...  ...         ...     ...
2019-11-18  {'JPY': 120.55}  2018-01-02  EUR  2019-12-31  120.55
2019-11-19  {'JPY': 120.46}  2018-01-02  EUR  2019-12-31  120.46
2019-11-20  {'JPY': 119.96}  2018-01-02  EUR  2019-12-31  119.96
2019-11-21  {'JPY': 120.46}  2018-01-02  EUR  2019-12-31  120.46
2019-11-22  {'JPY': 120.03}  2018-01-02  EUR  2019-12-31  120.03
2019-11-25  {'JPY': 119.88}  2018-01-02  EUR  2019-12-31  119.88
2019-11-26  {'JPY': 120.09}  2018-01-02  EUR  2019-12-31  120.09
2019-11-27  {'JPY': 120.18}  2018-01-02  EUR  2019-12-31  120.18
2019-11-28   {'JPY': 120.5}  2018-01-02  EUR  2019-12-31  120.50
2019-11-29  {'JPY': 120.43}  2018-01-02  EUR  2019-12-31  120.43
2019-12-02  {'JPY': 120.75}  2018-01-02  EUR  2019-12-31  120.75
2019-12-03  {'JPY': 120.39}  2018-01-02  EUR  2019-12-31  120.39
2019-12-04  {'JPY': 120.45}  2018-01-02  EUR  2019-12-31  120.45
2019-12-05  {'JPY': 120.69}  2018-01-02  EUR  2019-12-31  120.69
2019-12-06  {'JPY': 120.44}  2018-01-02  EUR  2019-12-31  120.44
2019-12-09  {'JPY': 120.15}  2018-01-02  EUR  2019-12-31  120.15
2019-12-10  {'JPY': 120.27}  2018-01-02  EUR  2019-12-31  120.27
2019-12-11  {'JPY': 120.44}  2018-01-02  EUR  2019-12-31  120.44
2019-12-12  {'JPY': 120.95}  2018-01-02  EUR  2019-12-31  120.95
2019-12-13  {'JPY': 122.43}  2018-01-02  EUR  2019-12-31  122.43
2019-12-16  {'JPY': 121.97}  2018-01-02  EUR  2019-12-31  121.97
2019-12-17  {'JPY': 122.31}  2018-01-02  EUR  2019-12-31  122.31
2019-12-18  {'JPY': 121.81}  2018-01-02  EUR  2019-12-31  121.81
2019-12-19  {'JPY': 121.73}  2018-01-02  EUR  2019-12-31  121.73
2019-12-20  {'JPY': 121.31}  2018-01-02  EUR  2019-12-31  121.31
2019-12-23  {'JPY': 121.18}  2018-01-02  EUR  2019-12-31  121.18
2019-12-24  {'JPY': 121.19}  2018-01-02  EUR  2019-12-31  121.19
2019-12-27  {'JPY': 122.23}  2018-01-02  EUR  2019-12-31  122.23
2019-12-30  {'JPY': 122.19}  2018-01-02  EUR  2019-12-31  122.19
2019-12-31  {'JPY': 121.94}  2018-01-02  EUR  2019-12-31  121.94

[510 rows x 5 columns]